version: '3'

volumes:
  minio-data:
    driver: local
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  db:
    image: "postgres:15.1-alpine"
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=beauty_polya
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    container_name: minio
    image: "minio/minio:latest"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
