spring:
  liquibase:
    enabled: false
  application:
    name: BeautyShopPolya
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/beauty_polya
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin